version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "loopback"
  api:
    image: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - db